### ISSUE TITLE
Key Binding erases file contents

### ISSUE THREAD

**Issue by gilbertoalbino** [Dickurt/vscode-php-formatter#3]
I have installed the extension and it happens that when I use the KeyBinding, it erases all the file contents.

**Comment by Dickurt** [comment]
Well that's not supposed to happen.

Could you provide any details? Such as the OS you're using, the keybinding, your settings, the context of the problem. Also, if you could turn on the `phpformatter.logging`, try formatting again, and then posting the console log, we might be able to shed a little light on the problem at hand.

If you could post the results here, then we might be able to figure this out together.

Thanks for bringing this to my attention.

**Comment by gilbertoalbino** [comment]
I running Visual Code 1.4 on Windows 10 64, with these user settings:

```
    "phpformatter.composer": true,
    "phpformatter.onSave": true,
    "phpformatter.level": "psr2",
    "phpformatter.logging": true
```

And this keybinding:

```
{
        "key": "ctrl+shift+l",
        "command": "phpformatter.fix",
        "when": "editorFocus"
    }
```

No output to console, by the way!

**Comment by Seidel-Michael** [comment]
Exact same Problem here. In Addition when I activate the onSave Feature nothing happens.

**Comment by Dickurt** [comment]
This issue gave me huge headache, but I finally managed to fix it.

First, I tried checking whether this had anything to do with reading the file using NodeJS's `fs` library. According to the [documentation](https://nodejs.org/docs/latest/api/fs.html#fs_fs_readfilesync_file_options), `fs.readFileSync` reads the _entire_ file.

So, then I immediately assumed this had something to do with character encoding. After having spent several hours on that, I came to the conclusion that it _could not be_ character encoding. I had completely isolated the issue from that.

So then I started fiddling around with reading files. Because I could positively confirm that the contents of the *.tmp files were properly written, the issue had to be with reading them. That's when I tried reading the file without using the `file descriptor`. Surprisingly, the entire file was read this time. Obviously, the file descriptor stored the wrong cursor position, which was used by `fs.readFileSync`.

The solution was to drop the `fs.readFileSync` method and use a read stream instead. This accepts an option to set the cursor position manually.

And that was that! Sorry for the long wait.
