### ISSUE TITLE
Use formatter API for better integration

### ISSUE THREAD

**Issue by jrieken** [Dickurt/vscode-php-formatter#5]
I'd recommend to use the languages API to register a formatting edits provider because it will allow for a better integration in VS Code. There is the [`registerDocumentFormattingEditProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4072)-function which is the way to introduce a formatter for certain document types. It will integrate you into the Format Code action (context menu, F1) and also into the Format On Save-feature.

It's more or less a matter of calling [this code](https://github.com/Dickurt/vscode-php-formatter/blob/master/extension.js#L54) from within [`DocumentFormattingEditProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2071)

**Comment by maxmatthews** [comment]
@jrieken @Dickurt made a pull request for this: https://github.com/Dickurt/vscode-php-formatter/pull/6

**Comment by Dickurt** [comment]
Thank you for actually looking at my code guys. I have been meaning to do this, but after the vscode 1.6.0 update came out, I didn't know where to look for the right events to hook into. So you pointed me into the right direction, @jrieken. Unfortunately, my extension is in plain old JS, so I couldn't figure out how to translate the TypeScript to plain JS. I struggled with that for a couple of hours and eventually gave up because I had other things to do.

@maxmatthews I saw your pull request and tested it locally. Unfortunately it doesn't seem to be working. I wrote a review on the pull request.

**Comment by jrieken** [comment]
Anything I can help you guys with?

**Comment by Dickurt** [comment]
I will be rewriting the plugin in TypeScript somewhere in the near future. That will help with integrating the new VSCode features more easily.

**Comment by Dickurt** [comment]
Resolved with conversion to TypeScript in latest milestone.
